name: Deploy to ECS EC2

on:
  push:
    branches:
      - main
      - vikula

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    # ===========================
    # Apply ECR (якщо потрібно)
    # ===========================
    - name: Terraform Apply ECR
      run: terraform apply -auto-approve -target=data.aws_ecr_repository.nginx || true
      working-directory: ./terraform

    # ===========================
    # Get ECR URL
    # ===========================
    - name: Get ECR repository URL
      id: ecr
      run: |
        REPO_URL=$(terraform -chdir=terraform output -raw ecr_repository_url 2>/dev/null)
        REPO_URL=$(echo "$REPO_URL" | tr -d '\r' | tr -d '\n')
        if [ -z "$REPO_URL" ]; then
          echo "ECR repository URL is empty! Make sure output is defined in Terraform."
          exit 1
        fi
        echo "ECR_REPOSITORY=$REPO_URL" >> $GITHUB_ENV
        echo "ECR URL: $REPO_URL"

    # ===========================
    # Build & Push Docker
    # ===========================
    - name: Build Docker image
      run: docker build -t nginx-hello ./app

    - name: Tag Docker image
      run: docker tag nginx-hello:latest "$ECR_REPOSITORY:latest"

    - name: Push Docker image
      run: docker push "$ECR_REPOSITORY:latest"

    # ===========================
    # Terraform Apply All (ECS, ALB ...)
    # ===========================
    - name: Terraform Apply All
      run: terraform apply -auto-approve
      working-directory: ./terraform
