name: Deploy to ECS EC2

on:
  push:
    branches:
      - main
      - vikula

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # 1Ô∏è‚É£ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # 3Ô∏è‚É£ Terraform formatting & validation
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      # 4Ô∏è‚É£ Apply only ECR to ensure the repository exists
      - name: Terraform Apply ECR
        run: terraform apply -auto-approve -target=aws_ecr_repository.nginx
        working-directory: ./terraform

      # 5Ô∏è‚É£ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ secrets.AWS_REGION }}

      # 6Ô∏è‚É£ Build, tag, and push Docker image to ECR
      - name: Build Docker image
        run: docker build -t nginx-hello ./app


      - name: Tag Docker image
        run: docker tag nginx-hello:latest public.ecr.aws/c5l2w2r3/nginx-hello:latest

      - name: Push Docker image to ECR
        run: docker push public.ecr.aws/c5l2w2r3/nginx-hello:latest

      # üîü Apply all Terraform resources
      - name: Terraform Apply All
        run: terraform apply -auto-approve
        working-directory: ./terraform
