name: Deploy to ECS EC2

on:
  push:
    branches:
      - main
      - vikula

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    # Створюємо ECR репозиторій окремо
    - name: Terraform Apply ECR
      run: terraform apply -auto-approve -target=aws_ecr_repository.nginx
      working-directory: ./terraform

    # Логін в ECR
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
      
    # Отримуємо URL ECR репозиторію
    - name: Get ECR repository URL
      id: ecr
      run: |
        REPO_URL=$(terraform -chdir=terraform output -raw ecr_repository_url | tr -d '\r')
        echo "ECR_REPOSITORY=$REPO_URL" >> $GITHUB_ENV

    # Build і Push Docker image
    - name: Build and Push Docker image
      run: |
        docker build -t nginx-hello ./app
        docker tag nginx-hello:latest $ECR_REPOSITORY:latest
        docker push $ECR_REPOSITORY:latest

    # Деплой всіх Terraform ресурсів (ECS, ALB, Security Groups)
    - name: Terraform Apply All
      run: terraform apply -auto-approve
      working-directory: ./terraform
