name: Deploy to ECS EC2

on:
  push:
    branches:
      - main
      - vikula

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: 386930771365
      ECR_REPO: ecs-nginx-hello-terraform-nginx
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Setup Terraform ----------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: TFLint
        uses: terraform-linters/tflint-action@v3
        with:
          working_directory: ./terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # ---------- Create ECR repository ----------
      - name: Terraform Apply ECR
        run: terraform apply -auto-approve -target=aws_ecr_repository.nginx
        working-directory: ./terraform

      # ---------- Docker build & push ----------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t ${{ env.ECR_REPO }} ./docker

      - name: Tag Docker image
        run: docker tag ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Push Docker image to ECR
        run: docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      # ---------- Deploy ECS / ALB ----------
      - name: Terraform Apply All
        run: terraform apply -auto-approve
        working-directory: ./terraform
