name: Deploy to ECS EC2

on:
  push:
    branches:
      - main
      - vikula

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    # Створюємо ECR репозиторій окремо
    - name: Terraform Apply ECR
      run: terraform apply -auto-approve -target=aws_ecr_repository.nginx
      working-directory: ./terraform

    # Логін в ECR
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    # Отримуємо URL репозиторію з Terraform
    - name: Get ECR repository URL
      id: ecr
      run: |
        REPO_URL=$(terraform -chdir=terraform output -raw ecr_repository_url | tr -d '\r' | tr -d '\n' | xargs)
        echo "ECR_REPOSITORY=$REPO_URL" >> $GITHUB_ENV
        echo "ECR URL: '$REPO_URL'"

    # Перевіряємо змінну перед використанням
    - name: Check ECR repository
      run: |
        echo "ECR_REPOSITORY='$ECR_REPOSITORY'"
        if [ -z "$ECR_REPOSITORY" ]; then
          echo "ECR_REPOSITORY is empty! Exiting..."
          exit 1
        fi

    # Tag Docker image
    - name: Tag Docker image
      run: |
        echo "Tagging Docker image as $ECR_REPOSITORY:latest"
        docker tag nginx-hello:latest "$ECR_REPOSITORY:latest"

    # Push Docker image
    - name: Push Docker image
      run: |
        echo "Pushing Docker image to $ECR_REPOSITORY"
        docker push "$ECR_REPOSITORY:latest"

    # Деплой всіх Terraform ресурсів (ECS, ALB, Security Groups)
    - name: Terraform Apply All
      run: terraform apply -auto-approve
      working-directory: ./terraform
