name: Deploy to ECS EC2

on:
  push:
    branches:
      - main
      - vikula

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: 386930771365
      ECR_REPO: ecs-nginx-hello-terraform-nginx
      IMAGE_TAG: latest

    steps:
      # ---------- Checkout code ----------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Configure AWS Credentials ----------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------- Setup Terraform ----------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # ---------- Terraform Init ----------
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # ---------- Terraform Format & Validate ----------
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      # ---------- Install and Run TFLint ----------
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint --chdir=./terraform

      # ---------- Terraform Apply ECR ----------
      - name: Terraform Apply ECR
        run: terraform apply -auto-approve -target=aws_ecr_repository.nginx
        working-directory: ./terraform

      # ---------- Docker build & push ----------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t ${{ env.ECR_REPO }} ./docker

      - name: Tag Docker image
        run: docker tag ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Push Docker image to ECR
        run: docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      # ---------- Terraform Deploy ECS / ALB ----------
      - name: Terraform Apply All
        run: terraform apply -auto-approve
        working-directory: ./terraform
